### ISSUE TITLE
Undocumented DLL changes

### ISSUE THREAD

**Issue by sekaiwish** [TsuyaC/mhfz-comfy-patch#1]
v1.1.0 includes modified DLL files which are not documented anywhere in the changelog, comparing the file shows 24 changed bytes. What do these bytes do?

**Comment by TsuyaC** [comment]
A comprehensive changelog is currently a WIP. The DLL's already got modified in 1.0.0 and the changes for both 1.0.0 and 1.1.0 are indeed listed in both of the release changelogs. The Bytes are adjusted g exchange rates. 

Since this isn't really a bug report, i will just go ahead and close this. 
Feel free to submit any clientside bugs (other than translation errors) as issues tho.
